
//! Autogenerated weights for `pallet_swallower`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-01-04, STEPS: `100`, REPEAT: 2, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/node-swallower
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_swallower
// --extrinsic
// *
// --steps
// 100
// --repeat
// 2
// --raw
// --output
// ./


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_swallower`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_swallower::WeightInfo for WeightInfo<T> {
	// Storage: Swallower OwnerSwallower (r:1 w:1)
	// Storage: Swallower AssetId (r:1 w:0)
	// Storage: Swallower AssetAmount (r:1 w:1)
	// Storage: Swallower GeneAmount (r:1 w:1)
	// Storage: Assets Metadata (r:1 w:0)
	// Storage: Swallower SwallowerConfig (r:1 w:0)
	// Storage: Swallower Swallowers (r:1 w:1)
	// Storage: Swallower Manager (r:1 w:0)
	// Storage: Assets Account (r:2 w:2)
	// Storage: Assets Asset (r:1 w:1)
	// Storage: Swallower SwallowerAmount (r:1 w:1)
	// Storage: Swallower SafeZone (r:0 w:1)
	fn burn_swallower() -> Weight {
		(391_255_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(12 as Weight))
			.saturating_add(T::DbWeight::get().writes(9 as Weight))
	}
}
