
//! Autogenerated weights for `pallet_swallower`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2021-12-31, STEPS: `100`, REPEAT: 2, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/node-swallower
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_swallower
// --extrinsic
// *
// --steps
// 100
// --repeat
// 2
// --raw
// --output
// ./


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_swallower`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_swallower::WeightInfo for WeightInfo<T> {
	// Storage: Swallower Admin (r:1 w:0)
	// Storage: Swallower AssetId (r:0 w:1)
	fn set_asset_id() -> Weight {
		(23_397_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Swallower Admin (r:0 w:1)
	fn set_admin() -> Weight {
		(21_442_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}
